#!/bin/bash
# ============================================================================
# install.sh — V17.1 — Pre-built standalone installer
# ============================================================================
# این نسخه:
# - npm install نمی‌خواد (همه‌چیز pre-built هست)
# - SESSION_SECRET قوی تولید می‌کنه
# - دیتابیس با permissions امن
# - systemd با user غیر root
# - فایروال + Nginx
# ============================================================================
set -e

SITE_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SITE_DIR"

VERSION="V17.1"
echo "=========================================="
echo "  نصب سایت شخصی $VERSION (Pre-built)"
echo "=========================================="
echo ""

# ============================================================================
# قدم ۱: Swap (اگه رم کمه)
# ============================================================================
echo "[1/8] Swap..."
if ! swapon --show | grep -q swap; then
    fallocate -l 2G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=2048
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    grep -q swapfile /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
    echo "  ✅ Swap ساخته شد"
else
    echo "  ✅ Swap هست"
fi

# ============================================================================
# قدم ۲: Node.js
# ============================================================================
echo ""
echo "[2/8] Node.js..."
if command -v node &> /dev/null; then
    NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
    if [ "$NODE_VER" -ge 20 ]; then
        echo "  ✅ Node.js نصبه ($(node -v))"
    else
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        apt install -y nodejs
        echo "  ✅ Node.js آپدیت شد"
    fi
else
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt install -y nodejs
    echo "  ✅ Node.js نصب شد ($(node -v))"
fi

# ============================================================================
# قدم ۳: ابزارهای ضروری
# ============================================================================
echo ""
echo "[3/8] Nginx + tools..."
if ! command -v nginx &> /dev/null; then
    apt update
    apt install -y nginx sqlite3 python3 ufw
    systemctl enable nginx
    systemctl start nginx
    echo "  ✅ Nginx نصب شد"
else
    apt install -y sqlite3 python3 ufw 2>/dev/null || true
    echo "  ✅ Nginx نصبه"
fi

# ============================================================================
# قدم ۴: فایروال
# ============================================================================
echo ""
echo "[4/8] فایروال..."
ufw allow 22/tcp 2>/dev/null || true
ufw allow 80/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
ufw --force enable 2>/dev/null || true
echo "  ✅ فایروال ست شد"

# ============================================================================
# قدم ۵: SESSION_SECRET قوی + .env امن
# ============================================================================
echo ""
echo "[5/8] SESSION_SECRET و .env..."
SECRET=$(openssl rand -hex 32)
mkdir -p db
chmod 700 db

# Webhook secrets هم تولید می‌کنیم
BALE_SECRET=$(openssl rand -hex 16)
TG_SECRET=$(openssl rand -hex 16)

cat > .env << EOF
# $VERSION — auto-generated by install.sh
DATABASE_URL="file:$SITE_DIR/db/custom.db"
NODE_ENV="production"
PORT=3000
HOSTNAME="0.0.0.0"
SESSION_SECRET="$SECRET"
NEXT_PUBLIC_SITE_URL="https://ehsanmorad.ir"
RECAPTCHA_SECRET=""
NEXT_PUBLIC_RECAPTCHA_SITEKEY=""
BALE_WEBHOOK_SECRET="$BALE_SECRET"
TELEGRAM_WEBHOOK_SECRET="$TG_SECRET"
EOF
chmod 600 .env
echo "  ✅ SESSION_SECRET قوی تولید شد (hex 64 chars)"
echo "  ✅ Webhook secrets هم تولید شد"

# ============================================================================
# قدم ۶: دیتابیس
# ============================================================================
echo ""
echo "[6/8] دیتابیس..."
touch db/custom.db
chmod 600 db/custom.db
rm -f db/custom.db-journal db/custom.db-wal db/custom.db-shm

# چک کن اگه جداول هست، skip
TABLES=$(sqlite3 db/custom.db "SELECT count(*) FROM sqlite_master WHERE type='table';" 2>/dev/null || echo "0")
if [ "$TABLES" = "0" ] || [ -z "$TABLES" ]; then
    echo "  seeding..."
    python3 scripts/seed_content.py 2>&1 | tail -1 || true
    python3 scripts/seed_equipment.py 2>&1 | tail -1 || true
    python3 scripts/seed_texts.py 2>&1 | tail -1 || true
    python3 scripts/seed_access_users.py 2>&1 | tail -1 || true
    echo "  ✅ دیتابیس seed شد"
else
    echo "  ✅ دیتابیس آماده ($TABLES جدول)"
fi

# ============================================================================
# قدم ۷: systemd service (با user غیر root)
# ============================================================================
echo ""
echo "[7/8] systemd service..."
# ساخت user مخصوص اگه نبود
if ! id -u ehsansite &>/dev/null; then
    useradd -r -s /bin/false -d "$SITE_DIR" ehsansite 2>/dev/null || true
fi
chown -R ehsansite:ehsansite "$SITE_DIR" 2>/dev/null || true

cat > /etc/systemd/system/personal-site.service << EOF
[Unit]
Description=Personal Site $VERSION
After=network.target

[Service]
Type=simple
User=ehsansite
Group=ehsansite
WorkingDirectory=$SITE_DIR
ExecStart=$(which node) server.js
Restart=always
RestartSec=10
Environment=NODE_ENV=production
Environment=HOSTNAME=0.0.0.0
Environment=PORT=3000
# امنیت اضافه
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=$SITE_DIR
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable personal-site
systemctl restart personal-site
sleep 5
echo "  ✅ سرویس اجرا شد"

# ============================================================================
# قدم ۸: Nginx
# ============================================================================
echo ""
echo "[8/8] Nginx..."
cp nginx-ehsanmorad.conf /etc/nginx/sites-available/nginx-ehsanmorad.conf 2>/dev/null || true
ln -sf /etc/nginx/sites-available/nginx-ehsanmorad.conf /etc/nginx/sites-enabled/nginx-ehsanmorad.conf 2>/dev/null || true
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
nginx -t 2>&1 && systemctl reload nginx
echo "  ✅ Nginx تنظیم شد"

# تست
if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ 2>/dev/null | grep -q "200"; then
    echo ""
    echo "  ✅ سایت بالا اومد!"
    SUCCESS=true
else
    echo ""
    echo "  ⚠ چک کن: journalctl -u personal-site -n 20"
    SUCCESS=false
fi

# ============================================================================
# خروجی نهایی
# ============================================================================
echo ""
echo "=========================================="
if [ "$SUCCESS" = "true" ]; then
    echo "  ✅ نصب کامل شد! ($VERSION)"
else
    echo "  ⚠ نصب انجام شد ولی سایت بالا نیومد"
    echo "  دستور بررسی: journalctl -u personal-site -n 30"
fi
echo "=========================================="
echo ""
echo "  آدرس‌ها:"
echo "    http://31.70.76.10:3000"
echo "    http://ehsanmorad.ir (اگه DNS ست شده)"
echo ""
echo "  ورود ادمین:"
echo "    http://ehsanmorad.ir/user-login"
echo "    username: admin"
echo "    password: admin123"
echo "    ⚠️ حتماً از پنل → تنظیمات → تغییر رمز عوض کن!"
echo ""
echo "  دستورات:"
echo "    systemctl status personal-site"
echo "    systemctl restart personal-site"
echo "    journalctl -u personal-site -f"
echo ""
echo "  ریست رمز ادمین (اگه فراموش کردی):"
echo "    sudo bash scripts/reset-admin-password.sh"
echo ""
echo "=========================================="
