#!/bin/bash
# ============================================================================
# install.sh — V17.2 — Pre-built standalone installer
# ============================================================================
# این نسخه:
# - npm install نمی‌خواد (همه‌چیز pre-built هست)
# - SESSION_SECRET قوی تولید می‌کنه
# - Webhook secrets هم تولید می‌کنه
# - دیتابیس با permissions امن
# - systemd با user غیر root
# - فایروال + Nginx
# - reCAPTCHA placeholder + راهنما
# - HTTPS setup با certbot (اگه دامنه ست شده)
# ============================================================================
set -e

SITE_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SITE_DIR"

VERSION="V17.5"
echo "=========================================="
echo "  نصب سایت شخصی $VERSION (Pre-built)"
echo "=========================================="
echo ""

# ============================================================================
# قدم ۱: Swap (اگه رم کمه)
# ============================================================================
echo "[1/10] Swap..."
if ! swapon --show | grep -q swap; then
    fallocate -l 2G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=2048
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    grep -q swapfile /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
    echo "  ✅ Swap ساخته شد"
else
    echo "  ✅ Swap هست"
fi

# ============================================================================
# قدم ۲: Node.js
# ============================================================================
echo ""
echo "[2/10] Node.js..."
if command -v node &> /dev/null; then
    NODE_VER=$(node -v | sed 's/v//' | cut -d. -f1)
    if [ "$NODE_VER" -ge 20 ]; then
        echo "  ✅ Node.js نصبه ($(node -v))"
    else
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        apt install -y nodejs
        echo "  ✅ Node.js آپدیت شد"
    fi
else
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt install -y nodejs
    echo "  ✅ Node.js نصب شد ($(node -v))"
fi

# ============================================================================
# قدم ۳: ابزارهای ضروری
# ============================================================================
echo ""
echo "[3/10] Nginx + tools + openssl..."
if ! command -v nginx &> /dev/null; then
    apt update
    apt install -y nginx sqlite3 python3 ufw certbot python3-certbot-nginx openssl
    systemctl enable nginx
    systemctl start nginx
    echo "  ✅ Nginx نصب شد"
else
    apt install -y sqlite3 python3 ufw certbot python3-certbot-nginx openssl 2>/dev/null || true
    echo "  ✅ Nginx نصبه"
fi
# بررسی نهایی openssl (مهم برای تولید SESSION_SECRET)
if ! command -v openssl &> /dev/null; then
    echo "  ❌ openssl پیدا نشد! نصب دستی: apt install -y openssl"
    exit 1
fi

# ============================================================================
# قدم ۴: فایروال
# ============================================================================
echo ""
echo "[4/10] فایروال..."
ufw allow 22/tcp 2>/dev/null || true
ufw allow 80/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
ufw --force enable 2>/dev/null || true
echo "  ✅ فایروال ست شد"

# ============================================================================
# قدم ۵: SESSION_SECRET قوی + .env امن
# ============================================================================
echo ""
echo "[5/10] SESSION_SECRET و .env..."
# Idempotent: اگه .env از قبل هست، SESSION_SECRET رو نگه دار
if [ -f .env ] && grep -q "^SESSION_SECRET=" .env; then
    EXISTING_SECRET=$(grep "^SESSION_SECRET=" .env | cut -d'"' -f2)
    if [ -n "$EXISTING_SECRET" ] && [ "$EXISTING_SECRET" != "build-placeholder" ]; then
        SECRET="$EXISTING_SECRET"
        echo "  ✅ SESSION_SECRET موجود نگه داشته شد (idempotent)"
    else
        SECRET=$(openssl rand -hex 32)
        echo "  ✅ SESSION_SECRET جدید تولید شد (قدیمی ضعیف بود)"
    fi
else
    SECRET=$(openssl rand -hex 32)
    echo "  ✅ SESSION_SECRET قوی تولید شد (openssl rand -hex 32)"
fi

# Webhook secrets — اگه هستن نگه دار
if [ -f .env ] && grep -q "^BALE_WEBHOOK_SECRET=" .env; then
    BALE_SECRET=$(grep "^BALE_WEBHOOK_SECRET=" .env | cut -d'"' -f2)
    [ -z "$BALE_SECRET" ] && BALE_SECRET=$(openssl rand -hex 16)
else
    BALE_SECRET=$(openssl rand -hex 16)
fi
if [ -f .env ] && grep -q "^TELEGRAM_WEBHOOK_SECRET=" .env; then
    TG_SECRET=$(grep "^TELEGRAM_WEBHOOK_SECRET=" .env | cut -d'"' -f2)
    [ -z "$TG_SECRET" ] && TG_SECRET=$(openssl rand -hex 16)
else
    TG_SECRET=$(openssl rand -hex 16)
fi

mkdir -p db
chmod 700 db

# reCAPTCHA — اگه از قبل هست، نگه‌دار
EXISTING_RECAPTCHA_SECRET=$(grep "^RECAPTCHA_SECRET=" .env 2>/dev/null | cut -d'"' -f2 || echo "")
EXISTING_RECAPTCHA_SITEKEY=$(grep "^NEXT_PUBLIC_RECAPTCHA_SITEKEY=" .env 2>/dev/null | cut -d'"' -f2 || echo "")

# Write .env (preserving existing values where present)
cat > .env << EOF
# V17.3 — auto-generated by install.sh
DATABASE_URL="file:$SITE_DIR/db/custom.db"
NODE_ENV="production"
PORT=3000
HOSTNAME="0.0.0.0"
SESSION_SECRET="$SECRET"
NEXT_PUBLIC_SITE_URL="https://ehsanmorad.ir"
RECAPTCHA_SECRET="$EXISTING_RECAPTCHA_SECRET"
NEXT_PUBLIC_RECAPTCHA_SITEKEY="$EXISTING_RECAPTCHA_SITEKEY"
BALE_WEBHOOK_SECRET="$BALE_SECRET"
TELEGRAM_WEBHOOK_SECRET="$TG_SECRET"
EOF
chmod 600 .env
echo "  ✅ Webhook secrets تولید شد"

# ============================================================================
# قدم ۶: دیتابیس
# ============================================================================
echo ""
echo "[6/10] دیتابیس..."
mkdir -p db
chmod 700 db
touch db/custom.db
chmod 600 db/custom.db
rm -f db/custom.db-journal db/custom.db-wal db/custom.db-shm

# اجرای prisma db push برای ساخت جداول (اگه نباشن)
TABLES=$(sqlite3 db/custom.db "SELECT count(*) FROM sqlite_master WHERE type='table';" 2>/dev/null || echo "0")
if [ "$TABLES" = "0" ] || [ -z "$TABLES" ]; then
    echo "  ساخت جداول با apply_schema.py (بدون نیاز به prisma CLI)..."
    python3 scripts/apply_schema.py 2>&1 | tail -3
    TABLES=$(sqlite3 db/custom.db "SELECT count(*) FROM sqlite_master WHERE type='table';" 2>/dev/null || echo "0")
    echo "  ✅ $TABLES جدول ساخته شد"
fi

# seeding اگه جداول خالی هستن
ADMIN_EXISTS=$(sqlite3 db/custom.db "SELECT count(*) FROM AccessUser WHERE username='admin';" 2>/dev/null || echo "0")
if [ "$ADMIN_EXISTS" = "0" ] || [ -z "$ADMIN_EXISTS" ]; then
    echo "  seeding..."
    python3 scripts/seed_content.py 2>&1 | tail -2 || echo "  ⚠ seed_content failed"
    python3 scripts/seed_equipment.py 2>&1 | tail -2 || echo "  ⚠ seed_equipment failed"
    python3 scripts/seed_texts.py 2>&1 | tail -2 || echo "  ⚠ seed_texts failed"
    python3 scripts/seed_access_users.py 2>&1 | tail -2 || echo "  ⚠ seed_access_users failed"
    echo "  ✅ دیتابیس seed شد"
else
    echo "  ✅ دیتابیس آماده (admin user exists)"
fi

# ============================================================================
# قدم ۷: کپی .env و db به standalone (اگه standalone هست)
# ============================================================================
echo ""
echo "[7/10] آماده‌سازی standalone..."
if [ -f server.js ]; then
    # حالت standalone — فایل‌ها از قبل هستن
    echo "  ✅ standalone آماده"
elif [ -d .next/standalone ]; then
    # حالت توسعه — کپی کن به standalone
    cp .env .next/standalone/.env
    chmod 600 .next/standalone/.env
    cp -r db .next/standalone/db 2>/dev/null || true
    chmod -R 600 .next/standalone/db/*.db 2>/dev/null || true
    cp -r .next/static .next/standalone/.next/ 2>/dev/null || true
    cp -r public .next/standalone/ 2>/dev/null || true
    SITE_DIR="$SITE_DIR/.next/standalone"
    cd "$SITE_DIR"
    echo "  ✅ آماده شد"
fi

# ============================================================================
# قدم ۸: systemd service (با user غیر root)
# ============================================================================
echo ""
echo "[8/10] systemd service..."
if ! id -u ehsansite &>/dev/null; then
    useradd -r -s /bin/false -d "$SITE_DIR" ehsansite 2>/dev/null || true
fi
chown -R ehsansite:ehsansite "$SITE_DIR" 2>/dev/null || true

cat > /etc/systemd/system/personal-site.service << EOF
[Unit]
Description=Personal Site $VERSION
After=network.target

[Service]
Type=simple
User=ehsansite
Group=ehsansite
WorkingDirectory=$SITE_DIR
ExecStart=$(which node) server.js
Restart=always
RestartSec=10
Environment=NODE_ENV=production
Environment=HOSTNAME=0.0.0.0
Environment=PORT=3000
# امنیت اضافه
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=$SITE_DIR
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable personal-site
systemctl restart personal-site
sleep 5
echo "  ✅ سرویس اجرا شد"

# ============================================================================
# قدم ۹: Nginx
# ============================================================================
echo ""
echo "[9/10] Nginx..."
cp nginx-ehsanmorad.conf /etc/nginx/sites-available/nginx-ehsanmorad.conf 2>/dev/null || true
ln -sf /etc/nginx/sites-available/nginx-ehsanmorad.conf /etc/nginx/sites-enabled/nginx-ehsanmorad.conf 2>/dev/null || true
rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
nginx -t 2>&1 && systemctl reload nginx
echo "  ✅ Nginx تنظیم شد"

# تست
if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ 2>/dev/null | grep -q "200"; then
    echo "  ✅ سایت بالا اومد"
    SUCCESS=true
else
    echo "  ⚠ چک کن: journalctl -u personal-site -n 20"
    SUCCESS=false
fi

# ============================================================================
# قدم ۱۰: HTTPS (اگه دامنه ست شده)
# ============================================================================
echo ""
echo "[10/10] HTTPS..."
DOMAIN_FOUND=""
for domain in ehsanmorad.ir ehsan-morad.ir ehsanmorad.id.ir; do
    if host "$domain" &>/dev/null; then
        DOMAIN_FOUND="$domain"
        break
    fi
done

if [ -n "$DOMAIN_FOUND" ]; then
    echo "  دامنه پیدا شد: $DOMAIN_FOUND"
    echo "  در حال دریافت SSL certificate..."
    if certbot --nginx -d "$DOMAIN_FOUND" -d "www.$DOMAIN_FOUND" --non-interactive --agree-tos --register-unsafely-without-email 2>&1 | tail -5; then
        echo "  ✅ HTTPS فعال شد"
        SITE_URL="https://$DOMAIN_FOUND"
    else
        echo "  ⚠ certbot ناموفق بود. بعداً دستی اجرا کن:"
        echo "    sudo certbot --nginx -d $DOMAIN_FOUND"
        SITE_URL="http://$DOMAIN_FOUND"
    fi
else
    echo "  ⚠ دامنه‌ای DNS ست نشده. فعلاً HTTP."
    SITE_URL="http://31.70.76.10:3000"
fi

# ============================================================================
# خروجی نهایی
# ============================================================================
echo ""
echo "=========================================="
if [ "$SUCCESS" = "true" ]; then
    echo "  ✅ نصب کامل شد! ($VERSION)"
else
    echo "  ⚠ نصب انجام شد ولی سایت بالا نیومد"
    echo "  دستور بررسی: journalctl -u personal-site -n 30"
fi
echo "=========================================="
echo ""
echo "  آدرس سایت:"
echo "    $SITE_URL"
echo ""
echo "  ورود ادمین:"
echo "    $SITE_URL/user-login"
echo "    username: admin"
echo "    password: admin123"
echo "    ⚠️ حتماً از پنل → تنظیمات → تغییر رمز عوض کن!"
echo ""
echo "  ⚠️ مهم — تنظیم reCAPTCHA:"
echo "    1. به https://www.google.com/recaptcha/admin برو"
echo "    2. یه سایت v2 ثبت کن (دامنه‌ات رو اضافه کن)"
echo "    3. Site Key و Secret Key رو بگیر"
echo "    4. این فایل رو ویرایش کن: $SITE_DIR/.env"
echo "       RECAPTCHA_SECRET=\"<secret-key>\""
echo "       NEXT_PUBLIC_RECAPTCHA_SITEKEY=\"<site-key>\""
echo "    5. سرویس رو restart کن: sudo systemctl restart personal-site"
echo ""
echo "  ⚠️ بدون reCAPTCHA، فرم تماس کار نمی‌کنه!"
echo ""
echo "  Webhook URLs (برای Bale/Telegram):"
if [ -n "$DOMAIN_FOUND" ]; then
    echo "    Bale:     https://$DOMAIN_FOUND/api/bale/webhook?secret=<SEE .env>"
    echo "    Telegram: https://$DOMAIN_FOUND/api/telegram/webhook?secret=<SEE .env>"
else
    echo "    Bale:     http://YOUR_IP:3000/api/bale/webhook?secret=<SEE .env>"
    echo "    Telegram: http://YOUR_IP:3000/api/telegram/webhook?secret=<SEE .env>"
fi
echo "    ⚠️ Secretها تو فایل .env هستن — با 'sudo cat .env' ببین"
echo "    ⚠️ این URL رو با کسی به اشتراک نذار!"
echo ""
echo "  دستورات:"
echo "    systemctl status personal-site"
echo "    systemctl restart personal-site"
echo "    journalctl -u personal-site -f"
echo ""
echo "  ریست رمز ادمین (اگه فراموش کردی):"
echo "    sudo bash scripts/reset-admin-password.sh"
echo ""
echo "=========================================="
